language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- 3.8-dev
install:
- pip install --upgrade pip
- pip install poetry
- poetry install
script:
- py.test --check-supported-comics --cov=webcomix
- mypy . --ignore-missing-imports
after_success:
- coveralls
before_deploy:
- poetry build
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: ucJXZbo9yUhloZrqP0uHWFs4Cw1wQOS0Lh97GuhTV1XXjNxFo/E3/TRNu+x+tdHntHlxBdrG97ONvlYle6NtNnDLMyZHD50eLEWEG99WLhR92Dy6ONEm8U2nV+YPYLD3U64LqMScuoXFBmwh6r/03ORjqddntlxRoJ9zf95PzkHxxNYdMf5BOVsR/d3IZVIIJG2lJzbFl2BXAuIiOPwc6UstEt1/A6I0Z6X3J3JHBwLdwW8sDPxTWK91+auzn+D4ApOpU6hLG1DVKqqTgbeFsBVBSvtRzLwFDpR0LteuUADsx1AHVGJjfI2chtd9aB6GGFOUI3syG4zsHtlTtddGmSVzWCGD4DU7pCBq+0cAU1OTJ9OS337W0tQtmipqSPrn0FSQXQAK1k2QnNwPK+xKH5ax8ssSNFl70ccCEsVcv7oWQEgAOsAx0yzsNbR6rGL2mDKGRluJLQ4OIogoVNDgJ351YTDxu3mhwIT5LumOQEIA0ROFu9zUSmKMnqMx1tywAMp2Es4rn5BKNGZB9+qmGAyB7mYBjJabbzv0zLSei+j9aFsakJopB9wAdyd0Q6GyP5wH1jX/URkqeLELCwnghbSJdanG0lfiUtbMblXP2vYnkVNS8cuE6fh/X3tjcKsEHqY7zFs6LX5rKh3VeUZydX2fmwwjJQh2JAPSsL9p9AM=
  file_glob: true
  file: dist/*
  draft: true
  on:
    repo: J-CPelletier/webcomix
    tags: true
    python: '3.5'
- provider: script
  script: poetry publish --username J-CPelletier --password $PYPI_PASSWORD
  skip_cleanup: true
  on:
    repo: J-CPelletier/webcomix
    tags: true
    branch: master
    python: '3.5'
env:
  global:
    secure: nSxIipu8xytPm1jclWe4HxXBNn4M0AgPqbHfv6+bJ/3G5xO4T02FDZOQr7KER/0fPVmskjC4KIO2fbye903LZNmsgTzJkZRDSCfrU7rBYeW7Vus0EMsea9NOzdnwwH2dEQJaQEJ4BX/y8lyJclQ3HylbFGqRRuaC18BA+XJQVu+XPk8s/PMFZx3SOll7CA4Jjn5UNEF/0/4wfBOPJCT7J8KNAtfJ87NTX+JkoeBuVeIbs/ycy03qKaBD2u2iAzfBpF9tsZLVNt9ZFczK6TYp3BB8SA0+CYwKd3qZRJgVnunxMFUQas81ZMDIuW0yiGq2EZPSjBxMfbiJVBMSENwHYla/2b+X014rH9JIkv/NT+gWjigUSm9mAwaxRLXgNfaqkem7P0WQ6e57fHurj72GIeCMzHJAjq8sJcMcjvKIqxQf0A0oYCd4RnRcedXd4tNOOThTQlDEDof1V1dLeyp7140yqr62gr6cCqcpYXxRKKrwKm4QiUCMZK1jKZMNuCGo3fY676xKxUZpCR8/qvkYr72MhFlSHEYu03NKE9/hBu3eBrhvq0roP6/YZXXpIbaW5GoFOHsm03TZRy/5nC8byaE6kWsH2Z0Azyd4TDHUI0B1isE5cQOmHp3QjY+V+VtjA/ThXqtHJGrEvCBFkCtXMHtPUJcIxH1bDL8b1xk19IM=
