name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 0


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-$
          restore-keys: |
            poetry-$
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          poetry install
      - name: Build
        run: poetry build
      - name: Run tests
        run: |
          PYTHONPATH=src/ poetry run python -m pytest --check-supported-comics --cov=webcomix
          PYTHONPATH=src/ poetry run python -m mypy . --ignore-missing-imports
      - name: Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: PYTHONPATH=src/ poetry run python -m coveralls
